//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXFnest {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DXFnest.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using ACadSharp;
        ///using ACadSharp.Entities;
        ///using CSMath;
        ///using System;
        ///using System.Collections.Generic;
        ///using System.ComponentModel;
        ///
        ///public class Shape2D
        ///{
        ///    public class ShapeParameters
        ///    {
        ///        [Category(&quot;OUTER SHAPE&quot;)]
        ///        public double LENGTH { get; set; }
        ///        [Category(&quot;OUTER SHAPE&quot;)]
        ///        public double WIDTH { get; set; }
        ///        [Category(&quot;OUTER SHAPE&quot;)]
        ///        public double CORNER_RADIUS { get; set; }
        ///
        ///        [Category(&quot;CORNER HOLES&quot;)]
        ///        public double D [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BasePlate {
            get {
                return ResourceManager.GetString("BasePlate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using ACadSharp;
        ///using ACadSharp.Entities;
        ///using ACadSharp.Tables;
        ///using ACadSharp.XData;
        ///using CSMath;
        ///using System;
        ///using System.Collections.Generic;
        ///using System.ComponentModel;
        ///using System.Text;
        ///
        ///public class Shape2D
        ///{
        ///    public class ShapeParameters
        ///    {
        ///        public enum BevelType { I, V, Y, X, K }
        ///
        ///        [Category(&quot;SHAPE&quot;)]
        ///        public double WIDTH { get; set; }
        ///
        ///        [Category(&quot;SHAPE&quot;)]
        ///        public double DIAMETER { get; set; }
        ///
        ///        [Category(&quot;SHAPE&quot;)]
        ///     [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BevelHolePlate {
            get {
                return ResourceManager.GetString("BevelHolePlate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using ACadSharp;
        ///using ACadSharp.Entities;
        ///using ACadSharp.Tables;
        ///using ACadSharp.XData;
        ///using CSMath;
        ///using System;
        ///using System.Collections.Generic;
        ///using System.ComponentModel;
        ///using System.Text;
        ///
        ///public class Shape2D
        ///{
        ///    public class ShapeParameters
        ///    {
        ///        public enum BevelType { I, V, Y, X, K }
        ///
        ///        [Category(&quot;OUTER SHAPE&quot;)]
        ///        public double WIDTH { get; set; }
        ///
        ///        [Category(&quot;OUTER SHAPE&quot;)]
        ///        public double BEVEL_CORNER_RADIUS { get; set; }
        ///
        ///        [C [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BevelPlate {
            get {
                return ResourceManager.GetString("BevelPlate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using ACadSharp;
        ///using ACadSharp.Entities;
        ///using CSMath;
        ///using System;
        ///using System.Collections.Generic;
        ///using System.ComponentModel;
        ///using System.Text;
        ///
        ///public class Shape2D
        ///{
        ///    public class ShapeParameters
        ///    {
        ///        [Category(&quot;OUTER SHAPE&quot;)]
        ///        public double DIAMETER { get; set; }
        ///
        ///        public ShapeParameters()
        ///        {
        ///            DIAMETER = 250.0;
        ///        }
        ///    }
        ///
        ///    public CadDocument Run(ShapeParameters parameters)
        ///    {
        ///        CadDocument doc = new CadDocument( [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Circle {
            get {
                return ResourceManager.GetString("Circle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using ACadSharp;
        ///using ACadSharp.Entities;
        ///using CSMath;
        ///using System;
        ///using System.Collections.Generic;
        ///using System.ComponentModel;
        ///using System.Drawing.Drawing2D;
        ///using System.Drawing;
        ///using System.Text;
        ///
        ///public class Shape2D
        ///{
        ///    public class ShapeParameters
        ///    {
        ///        [Category(&quot;TEXT&quot;)]
        ///        public string TEXT { get; set; }
        ///
        ///        [Category(&quot;TEXT&quot;)]
        ///        public string FONT_NAME { get; set; }
        ///
        ///        [Category(&quot;TEXT&quot;)]
        ///        public double CHAR_HEIGHT { get; set; }
        ///
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Lettering {
            get {
                return ResourceManager.GetString("Lettering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using ACadSharp;
        ///using ACadSharp.Entities;
        ///using ACadSharp.Tables;
        ///using CSMath;
        ///using System;
        ///using System.Collections.Generic;
        ///using System.ComponentModel;
        ///
        ///public class Shape2D
        ///{
        ///    public class ShapeParameters
        ///    {
        ///        [Category(&quot;OUTER SHAPE&quot;)]
        ///        public double LENGTH { get; set; }
        ///        [Category(&quot;OUTER SHAPE&quot;)]
        ///        public double WIDTH { get; set; }
        ///        [Category(&quot;MARKING&quot;)]
        ///        public double MARKING_OFFSET { get; set; }
        ///
        ///        public ShapeParameters()
        ///    [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Marking {
            get {
                return ResourceManager.GetString("Marking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using ACadSharp;
        ///using ACadSharp.Entities;
        ///using System;
        ///using System.Collections.Generic;
        ///using System.ComponentModel;
        ///
        ///public class Shape2D
        ///{
        ///    public class ShapeParameters
        ///    {
        ///        [Category(&quot;CATEGORY&quot;)]
        ///        public double DBL_PARAM { get; set; }
        ///
        ///        public ShapeParameters()
        ///        {
        ///            DBL_PARAM = 100.0;
        ///        }
        ///    }
        ///
        ///    public CadDocument Run(ShapeParameters parameters)
        ///    {
        ///        CadDocument doc = new CadDocument();
        ///
        ///        // doc.ModelSpace.Enti [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NewShape2D {
            get {
                return ResourceManager.GetString("NewShape2D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using ACadSharp;
        ///using ACadSharp.Entities;
        ///using CSMath;
        ///using System;
        ///using System.Collections.Generic;
        ///using System.ComponentModel;
        ///using System.Text;
        ///
        ///public class Shape2D
        ///{
        ///    public class ShapeParameters
        ///    {
        ///        [Category(&quot;OUTER SHAPE&quot;)]
        ///        public double LENGTH { get; set; }
        ///        [Category(&quot;OUTER SHAPE&quot;)]
        ///        public double WIDTH { get; set; }
        ///        [Category(&quot;OPEN CUT&quot;)]
        ///        public double OFFSET { get; set; }
        ///
        ///        public ShapeParameters()
        ///        {
        ///     [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string OpenCut {
            get {
                return ResourceManager.GetString("OpenCut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using ACadSharp;
        ///using ACadSharp.Entities;
        ///using CSMath;
        ///using System;
        ///using System.Collections.Generic;
        ///using System.ComponentModel;
        ///using System.Drawing.Text;
        ///using System.Drawing;
        ///using System.IO;
        ///using System.Reflection;
        ///using System.Runtime.InteropServices;
        ///using System.Text;
        ///using System.Drawing.Drawing2D;
        ///
        ///public class Shape2D
        ///{
        ///    public class ShapeParameters
        ///    {
        ///        [Category(&quot;SHAPE&quot;)]
        ///        public string SEED { get; set; }
        ///
        ///        [Category(&quot;SHAPE&quot;)]
        ///        public  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RandomNest {
            get {
                return ResourceManager.GetString("RandomNest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using ACadSharp;
        ///using ACadSharp.Entities;
        ///using CSMath;
        ///using System;
        ///using System.Collections.Generic;
        ///using System.ComponentModel;
        ///using System.Drawing;
        ///using System.Drawing.Drawing2D;
        ///
        ///public class Shape2D
        ///{
        ///    public class ShapeParameters
        ///    {
        ///        [Category(&quot;SHAPE&quot;)]
        ///        [TypeConverter(typeof(CharListConverter))]
        ///        public string SHAPE { get; set; }
        ///
        ///        [Category(&quot;SHAPE&quot;)]
        ///        public double HEIGHT { get; set; }
        ///
        ///        public ShapeParameters()
        ///        {
        ///   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RandomShape {
            get {
                return ResourceManager.GetString("RandomShape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using ACadSharp;
        ///using ACadSharp.Entities;
        ///using CSMath;
        ///using System;
        ///using System.Collections.Generic;
        ///using System.ComponentModel;
        ///using System.Text;
        ///
        ///public class Shape2D
        ///{
        ///    public class ShapeParameters
        ///    {
        ///        [Category(&quot;OUTER SHAPE&quot;)]
        ///        public double LENGTH { get; set; }
        ///        [Category(&quot;OUTER SHAPE&quot;)]
        ///        public double WIDTH { get; set; }
        ///
        ///        public ShapeParameters()
        ///        {
        ///            LENGTH = 400.0;
        ///            WIDTH = 400.0;
        ///        }
        ///    }
        ///
        ///    [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Rectangle {
            get {
                return ResourceManager.GetString("Rectangle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using ACadSharp;
        ///using ACadSharp.Entities;
        ///using CSMath;
        ///using System;
        ///using System.Collections.Generic;
        ///using System.ComponentModel;
        ///
        ///public class Shape2D
        ///{
        ///    public class ShapeParameters
        ///    {
        ///        [Category(&quot;OUTER SHAPE&quot;)]
        ///        public int N_FACES { get; set; }
        ///        [Category(&quot;OUTER SHAPE&quot;)]
        ///        public double CIRCUMSCRIBED_DIAMETER { get; set; }
        ///
        ///        public ShapeParameters()
        ///        {
        ///            N_FACES = 3;
        ///            CIRCUMSCRIBED_DIAMETER = 250.0;
        ///        }
        ///    [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RegularPoly {
            get {
                return ResourceManager.GetString("RegularPoly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using ACadSharp;
        ///using ACadSharp.Entities;
        ///using CSMath;
        ///using System.ComponentModel;
        ///
        ///public class Shape2D
        ///{
        ///    public class ShapeParameters
        ///    {
        ///        [Category(&quot;OUTER SHAPE&quot;)]
        ///        public double OUTTER_DIAMETER { get; set; }
        ///
        ///        [Category(&quot;INNER SHAPE&quot;)]
        ///        public double INNER_DIAMETER { get; set; }
        ///
        ///        public ShapeParameters()
        ///        {
        ///            OUTTER_DIAMETER = 400.0;
        ///            INNER_DIAMETER = 250.0;
        ///        }
        ///    }
        ///
        ///    public CadDocument Run(ShapePar [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Ring {
            get {
                return ResourceManager.GetString("Ring", resourceCulture);
            }
        }
    }
}
